#!/usr/bin/env ts-node
/**
 * simulate-upgrade.ts
 *
 * Replays representative state snapshots against a proposed schema to detect
 * read-path panics, type mismatches, and missing storage keys before an
 * upgrade is approved.
 *
 * The simulator does NOT execute the WASM binary directly (that would require
 * a full Soroban sandbox).  Instead it:
 *
 *   1. Loads a state snapshot (JSON exported from the chain or generated by
 *      the contract's test suite via test_snapshots/).
 *   2. Loads the proposed schema for that contract.
 *   3. For every storage key in the snapshot, checks that:
 *        a. The key still exists in the proposed schema.
 *        b. The value shape in the snapshot is compatible with the proposed
 *           value type (field names present, types match).
 *        c. Composite key params haven't changed.
 *   4. Reports a simulation result per contract with PASS / WARN / FAIL.
 *
 * Full WASM-level simulation can be layered on top later by piping the
 * snapshot data into stellar-cli contract invoke --snapshot.
 *
 * Usage:
 *   ts-node scripts/simulate-upgrade.ts \
 *     --schema contracts/schemas/core_vault.schema.json \
 *     --snapshot contracts/core_vault/test_snapshots/test/test_force_exit_happy_path.1.json \
 *     [--migrations contracts/migrations/core_vault.migrations.json]
 *
 * Or for the whole suite:
 *   ts-node scripts/simulate-upgrade.ts --all \
 *     [--schemas-dir contracts/schemas] \
 *     [--snapshots-root contracts]
 */

import * as fs from "fs";
import * as path from "path";
import type { ContractStorageSchema, StorageKeySchema } from "./extract-storage-schema";
import type { MigrationRecord } from "./compare-storage-schemas";

// ─── Snapshot types (Soroban test-snapshot JSON format) ───────────────────────

interface SnapshotEntry {
  key: unknown;
  val: unknown;
  storage?: "instance" | "persistent" | "temporary";
}

interface ContractStateSnapshot {
  /** Optional: contract name for labelling */
  contract?: string;
  ledger?: {
    sequence?: number;
    timestamp?: number;
  };
  entries?: SnapshotEntry[];
  /** Flattened key→value map variant (simpler tooling output) */
  storage?: Record<string, unknown>;
}

// ─── Simulation result types ─────────────────────────────────────────────────

export type SimulationStatus = "PASS" | "WARN" | "FAIL";

export interface KeySimulationResult {
  key: string;
  status: SimulationStatus;
  message: string;
}

export interface SimulationReport {
  contract: string;
  snapshot_file: string;
  schema_file: string;
  status: SimulationStatus;
  key_results: KeySimulationResult[];
  summary: string;
  simulated_at: string;
}

// ─── Value type compatibility checker ────────────────────────────────────────

/**
 * Returns true if the snapshot value appears compatible with the expected type.
 * This is best-effort: complex XDR values may not fully roundtrip through JSON,
 * so we focus on structural shape checks.
 */
function isValueCompatible(value: unknown, expectedType: string): boolean {
  if (expectedType === "unknown") return true; // extractor could not infer type

  // Numeric primitives
  if (["i128", "u128", "i64", "u64", "u32", "i32", "bool"].includes(expectedType)) {
    return (
      typeof value === "number" ||
      typeof value === "bigint" ||
      typeof value === "boolean" ||
      // Some serialisations use string for i128
      typeof value === "string"
    );
  }

  // Address
  if (expectedType === "Address") {
    return typeof value === "string" || (typeof value === "object" && value !== null);
  }

  // BytesN<N> / Bytes
  if (expectedType.startsWith("Bytes")) {
    return (
      typeof value === "string" || // hex-encoded
      Array.isArray(value) ||
      (typeof value === "object" && value !== null)
    );
  }

  // Vec<T>
  if (expectedType.startsWith("Vec<")) {
    return Array.isArray(value) || (typeof value === "object" && value !== null);
  }

  // Struct type (object shape)
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return true; // structural; field checks done separately by struct comparator
  }

  // Enum value (could be a string variant name or object with variant+value)
  if (typeof value === "string" || (typeof value === "object" && value !== null)) {
    return true;
  }

  return true; // fallback: warn elsewhere
}

// ─── Snapshot entry key extraction ───────────────────────────────────────────

function extractKeyName(entry: SnapshotEntry): string | null {
  const key = entry.key;
  if (typeof key === "string") return key;
  if (typeof key === "object" && key !== null) {
    // Soroban snapshot format: { "DataKey": { "Config": null } }
    // or { "symbol": "last_out" }
    const obj = key as Record<string, unknown>;
    if ("symbol" in obj && typeof obj["symbol"] === "string") return obj["symbol"];
    if ("DataKey" in obj) {
      const dkVal = obj["DataKey"] as Record<string, unknown>;
      if (typeof dkVal === "string") return dkVal;
      return Object.keys(dkVal)[0] ?? null;
    }
    // Fallback: first key of the object
    return Object.keys(obj)[0] ?? null;
  }
  return null;
}

// ─── Simulate a single snapshot against a schema ─────────────────────────────

export function simulateSnapshot(
  schema: ContractStorageSchema,
  snapshot: ContractStateSnapshot,
  snapshotFile: string,
  schemaFile: string,
  _migrations: MigrationRecord[] = []
): SimulationReport {
  const keyResults: KeySimulationResult[] = [];
  const keyMap = new Map<string, StorageKeySchema>(
    schema.data_keys.map((k) => [k.key, k])
  );

  // Normalise snapshot to a list of { key, value } pairs
  const pairs: Array<{ keyName: string; value: unknown }> = [];

  if (snapshot.entries) {
    for (const entry of snapshot.entries) {
      const keyName = extractKeyName(entry);
      if (keyName) pairs.push({ keyName, value: entry.val });
    }
  }

  if (snapshot.storage) {
    for (const [k, v] of Object.entries(snapshot.storage)) {
      pairs.push({ keyName: k, value: v });
    }
  }

  if (pairs.length === 0) {
    return {
      contract: schema.contract,
      snapshot_file: snapshotFile,
      schema_file: schemaFile,
      status: "WARN",
      key_results: [
        {
          key: "(all)",
          status: "WARN",
          message: "No storage entries found in snapshot — ensure the snapshot format is compatible",
        },
      ],
      summary: "No entries to simulate",
      simulated_at: new Date().toISOString(),
    };
  }

  for (const { keyName, value } of pairs) {
    const schemaDef = keyMap.get(keyName);

    if (!schemaDef) {
      // Key in snapshot not present in schema — could be a removed key
      keyResults.push({
        key: keyName,
        status: "FAIL",
        message: `Key "${keyName}" exists in snapshot but is absent from proposed schema — upgrade would orphan this state`,
      });
      continue;
    }

    // Check value type compatibility
    if (!isValueCompatible(value, schemaDef.value_type)) {
      keyResults.push({
        key: keyName,
        status: "FAIL",
        message: `Value shape mismatch: expected type ${schemaDef.value_type}, snapshot value is ${JSON.stringify(value).slice(0, 80)}`,
      });
      continue;
    }

    // Check struct fields if value is an object and we have struct definitions
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      const structDef = schema.structs.find((s) => s.name === schemaDef.value_type);
      if (structDef) {
        const valueObj = value as Record<string, unknown>;
        const snapshotFields = Object.keys(valueObj);
        const schemaFields = structDef.fields.map((f) => f.name);
        const missingInSnapshot = schemaFields.filter(
          (f) => !snapshotFields.includes(f)
        );
        const unknownInSchema = snapshotFields.filter(
          (f) => !schemaFields.includes(f)
        );

        if (unknownInSchema.length > 0) {
          // Fields in snapshot not in schema — removed in upgrade
          keyResults.push({
            key: keyName,
            status: "FAIL",
            message: `Struct ${schemaDef.value_type} has fields in snapshot that are absent from proposed schema: ${unknownInSchema.join(", ")}`,
          });
          continue;
        }

        if (missingInSnapshot.length > 0) {
          // Fields in schema not in snapshot — could be new optional fields
          keyResults.push({
            key: keyName,
            status: "WARN",
            message: `Struct ${schemaDef.value_type} has new fields not present in snapshot: ${missingInSnapshot.join(", ")} (acceptable if added at end with defaults)`,
          });
          continue;
        }
      }
    }

    keyResults.push({
      key: keyName,
      status: "PASS",
      message: `Compatible with schema type ${schemaDef.value_type}`,
    });
  }

  // Also check for required schema keys that are not in the snapshot
  // (no-entries keys like Config are expected but warn if they seem absent)
  for (const sk of schema.data_keys) {
    if (
      sk.storage_class === "Instance" &&
      sk.key_params.length === 0 &&
      !pairs.find((p) => p.keyName === sk.key)
    ) {
      keyResults.push({
        key: sk.key,
        status: "WARN",
        message: `Instance key "${sk.key}" not present in snapshot — contract may not be initialized in this snapshot`,
      });
    }
  }

  // Compute overall status
  let status: SimulationStatus = "PASS";
  for (const r of keyResults) {
    if (r.status === "FAIL") { status = "FAIL"; break; }
    if (r.status === "WARN") status = "WARN";
  }

  const failCount = keyResults.filter((r) => r.status === "FAIL").length;
  const warnCount = keyResults.filter((r) => r.status === "WARN").length;
  const passCount = keyResults.filter((r) => r.status === "PASS").length;

  const lines = [
    `Contract: ${schema.contract}  [${status}]`,
    `  Snapshot: ${path.basename(snapshotFile)}`,
    `  Pass: ${passCount}  Warn: ${warnCount}  Fail: ${failCount}`,
  ];
  for (const r of keyResults.filter((r) => r.status !== "PASS")) {
    lines.push(`  [${r.status}] ${r.key}: ${r.message}`);
  }

  return {
    contract: schema.contract,
    snapshot_file: snapshotFile,
    schema_file: schemaFile,
    status,
    key_results: keyResults,
    summary: lines.join("\n"),
    simulated_at: new Date().toISOString(),
  };
}

// ─── CLI ─────────────────────────────────────────────────────────────────────

function loadJson<T>(p: string): T {
  return JSON.parse(fs.readFileSync(p, "utf-8")) as T;
}

function runAll(schemasDir: string, snapshotsRoot: string): boolean {
  let overallPass = true;

  const schemaFiles = fs
    .readdirSync(schemasDir)
    .filter((f) => f.endsWith(".schema.json"));

  for (const sf of schemaFiles) {
    const schema = loadJson<ContractStorageSchema>(path.join(schemasDir, sf));
    const contractName = schema.contract;

    // Find all snapshots for this contract
    const snapshotsDir = path.join(snapshotsRoot, contractName, "test_snapshots");
    if (!fs.existsSync(snapshotsDir)) continue;

    const snapshotFiles: string[] = [];
    for (const sub of fs.readdirSync(snapshotsDir)) {
      const subPath = path.join(snapshotsDir, sub);
      if (fs.statSync(subPath).isDirectory()) {
        for (const f of fs.readdirSync(subPath)) {
          if (f.endsWith(".json")) {
            snapshotFiles.push(path.join(subPath, f));
          }
        }
      } else if (sub.endsWith(".json")) {
        snapshotFiles.push(subPath);
      }
    }

    for (const snapshotFile of snapshotFiles) {
      const snapshot = loadJson<ContractStateSnapshot>(snapshotFile);
      const migrationsPath = path.join(
        snapshotsRoot,
        "..",
        "contracts",
        "migrations",
        `${contractName}.migrations.json`
      );
      const migrations: MigrationRecord[] = fs.existsSync(migrationsPath)
        ? loadJson<MigrationRecord[]>(migrationsPath)
        : [];

      const report = simulateSnapshot(
        schema,
        snapshot,
        snapshotFile,
        path.join(schemasDir, sf),
        migrations
      );

      console.log(report.summary);
      if (report.status === "FAIL") overallPass = false;
    }
  }

  return overallPass;
}

function main() {
  const args = process.argv.slice(2);
  let schemaPath: string | undefined;
  let snapshotPath: string | undefined;
  let migrationsPath: string | undefined;
  let runAllFlag = false;
  let schemasDir = path.resolve(__dirname, "../contracts/schemas");
  let snapshotsRoot = path.resolve(__dirname, "../contracts");

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--schema" && args[i + 1]) schemaPath = args[++i];
    else if (args[i] === "--snapshot" && args[i + 1]) snapshotPath = args[++i];
    else if (args[i] === "--migrations" && args[i + 1]) migrationsPath = args[++i];
    else if (args[i] === "--all") runAllFlag = true;
    else if (args[i] === "--schemas-dir" && args[i + 1]) schemasDir = args[++i];
    else if (args[i] === "--snapshots-root" && args[i + 1]) snapshotsRoot = args[++i];
  }

  if (runAllFlag) {
    const pass = runAll(schemasDir, snapshotsRoot);
    process.exit(pass ? 0 : 1);
    return;
  }

  if (!schemaPath || !snapshotPath) {
    console.error(
      "Usage: simulate-upgrade --schema <path> --snapshot <path> [--migrations <path>]\n" +
        "       simulate-upgrade --all [--schemas-dir <path>] [--snapshots-root <path>]"
    );
    process.exit(1);
  }

  const schema = loadJson<ContractStorageSchema>(schemaPath);
  const snapshot = loadJson<ContractStateSnapshot>(snapshotPath);
  const migrations: MigrationRecord[] = migrationsPath
    ? loadJson<MigrationRecord[]>(migrationsPath)
    : [];

  const report = simulateSnapshot(schema, snapshot, snapshotPath, schemaPath, migrations);
  console.log(report.summary);

  if (report.status === "FAIL") process.exit(1);
  if (report.status === "WARN") process.exit(0); // warnings are non-fatal in CI
  process.exit(0);
}

if (require.main === module) {
  main();
}
