/**
 * auditLog.entity.ts  (Issue #344 — Security-Grade Audit Ledger)
 *
 * TypeORM entity for the `audit_log` table, extended with:
 *   - correlationId   — distributed trace identifier
 *   - actorId / actorServiceId — canonical "who" fields
 *   - category        — event taxonomy bucket (Auth/Admin/Execution/Policy/Integration)
 *   - eventHash       — SHA-256 hash of immutable event fields (tamper-evidence)
 *   - previousHash    — SHA-256 hash of the preceding entry (chain integrity)
 *
 * Legacy AuditAction / AuditSeverity enums are preserved for backward-compat.
 * New code should use the typed enums from auditEvent.types.ts.
 */

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from "typeorm";
import { EventCategory, AuditEventSeverity } from "./auditEvent.types";

// ─── Legacy Enums (backward-compat) ──────────────────────────────────────────

export enum AuditAction {
  // Auth
  LOGIN_SUCCESS = "login_success",
  LOGIN_FAILED = "login_failed",
  LOGOUT = "logout",
  TOKEN_REFRESH = "token_refresh",
  PASSWORD_RESET_REQUEST = "password_reset_request",
  PASSWORD_RESET_SUCCESS = "password_reset_success",
  PASSWORD_RESET_FAILED = "password_reset_failed",
  EMAIL_VERIFICATION_SENT = "email_verification_sent",
  EMAIL_VERIFICATION_SUCCESS = "email_verification_success",

  // User management
  USER_CREATED = "user_created",
  USER_UPDATED = "user_updated",
  USER_DELETED = "user_deleted",

  // Trading/Transaction
  TRADE_INITIATED = "trade_initiated",
  TRADE_CONFIRMED = "trade_confirmed",
  TRADE_FAILED = "trade_failed",
  SWAP_EXECUTED = "swap_executed",
  TRANSFER_INITIATED = "transfer_initiated",
  TRANSFER_COMPLETED = "transfer_completed",

  // Wallet
  WALLET_FUNDED = "wallet_funded",
  WALLET_DEPLOYED = "wallet_deployed",

  // Security
  UNAUTHORIZED_ACCESS = "unauthorized_access",
  PERMISSION_DENIED = "permission_denied",
  SUSPICIOUS_ACTIVITY = "suspicious_activity",
  ABUSE_POLICY_DECISION = "abuse_policy_decision",
  KYC_POLICY_DECISION = "kyc_policy_decision",

  // Data
  DATA_EXPORT = "data_export",
  SENSITIVE_DATA_ACCESS = "sensitive_data_access",

  // Bot commands
  BOT_COMMAND_START = "bot_command_start",
  BOT_COMMAND_HELP = "bot_command_help",
  BOT_COMMAND_THREAD = "bot_command_thread",
  BOT_COMMAND_SPONSOR = "bot_command_sponsor",
  BOT_COMMAND_TRUSTLINE = "bot_command_trustline",
  BOT_COMMAND_DASHBOARD = "bot_command_dashboard",
  BOT_COMMAND_VALIDATE = "bot_command_validate",
  BOT_COMMAND_BALANCE = "bot_command_balance",
  BOT_COMMAND_SWAP = "bot_command_swap",
  BOT_COMMAND_PORTFOLIO = "bot_command_portfolio",
}

export enum AuditSeverity {
  INFO = "info",
  WARNING = "warning",
  ERROR = "error",
  CRITICAL = "critical",
}

// ─── Entity ───────────────────────────────────────────────────────────────────

/**
 * Composite indexes are ordered for SecOps forensic query patterns:
 *
 *   (category, createdAt)        — enumerate all events in a bucket over time
 *   (correlationId, createdAt)   — reconstruct a full distributed trace
 *   (actorId, createdAt)         — actor-centric timeline
 *   (action, createdAt)          — action-specific reporting
 *   (severity, createdAt)        — alert-severity dashboards
 *   (userId, createdAt)          — user timeline (legacy compat)
 *   createdAt (standalone)       — range scans / retention purge
 */
@Entity("audit_log")
@Index("idx_audit_category_time", ["category", "createdAt"])
@Index("idx_audit_correlation_time", ["correlationId", "createdAt"])
@Index("idx_audit_actor_time", ["actorId", "createdAt"])
@Index("idx_audit_action_time", ["action", "createdAt"])
@Index("idx_audit_severity_time", ["severity", "createdAt"])
@Index("idx_audit_user_time", ["userId", "createdAt"])
export class AuditLog {
  // ── Primary Key ────────────────────────────────────────────────────────────

  @PrimaryGeneratedColumn("uuid")
  id!: string;

  // ── Distributed Tracing ────────────────────────────────────────────────────

  /**
   * Correlation ID propagated from the inbound HTTP header
   * (`x-correlation-id` or `x-request-id`).  Ties every downstream
   * audit event generated by one user request together.
   */
  @Column({ type: "varchar", nullable: true })
  @Index("idx_audit_correlation_id")
  correlationId?: string;

  // ── Actor (who) ────────────────────────────────────────────────────────────

  /** Authenticated user ID — may be null for anonymous / service actions */
  @Column({ type: "varchar", nullable: true })
  @Index("idx_audit_user_id")
  userId?: string;

  /** Canonical actor ID — mirrors userId for human actors, serviceId otherwise */
  @Column({ type: "varchar", nullable: true })
  @Index("idx_audit_actor_id")
  actorId?: string;

  /** Service / bot identifier for non-human actors */
  @Column({ type: "varchar", nullable: true })
  actorServiceId?: string;

  /** Roles held by the actor at the time of the event */
  @Column({ type: "simple-array", nullable: true })
  actorRoles?: string[];

  // ── Action + Category ──────────────────────────────────────────────────────

  /** Typed action string, e.g. "auth.login.success" */
  @Column({ type: "varchar" })
  action!: string;

  /** Taxonomy bucket: Auth | Admin | Execution | Policy | Integration */
  @Column({
    type: "varchar",
    nullable: true,
    default: null,
  })
  category?: EventCategory;

  // ── Severity + Outcome ─────────────────────────────────────────────────────

  @Column({ type: "varchar", default: AuditSeverity.INFO })
  severity!: AuditSeverity | AuditEventSeverity;

  @Column({ type: "boolean", default: true })
  success!: boolean;

  @Column({ type: "text", nullable: true })
  errorMessage?: string;

  // ── Request Context ────────────────────────────────────────────────────────

  @Column({ type: "varchar", nullable: true })
  ipAddress?: string;

  @Column({ type: "varchar", nullable: true })
  userAgent?: string;

  /** HTTP method + path that triggered the event, e.g. "POST /api/trade" */
  @Column({ type: "varchar", nullable: true })
  resource?: string;

  // ── Metadata (PII-scrubbed) ────────────────────────────────────────────────

  /** Arbitrary event context — automatically scrubbed for PII before persistence */
  @Column({ type: "jsonb", nullable: true })
  metadata?: Record<string, unknown>;

  // ── Tamper-Evidence ────────────────────────────────────────────────────────

  /**
   * SHA-256 hex digest of this event's immutable canonical fields.
   * Verifying the hash detects any post-write row mutation.
   */
  @Column({ type: "varchar", length: 64, nullable: true })
  eventHash?: string;

  /**
   * SHA-256 hex digest of the immediately preceding event.
   * Forms a linked hash-chain; a broken chain signals tampering.
   */
  @Column({ type: "varchar", length: 64, nullable: true })
  previousHash?: string;

  // ── Timestamps ─────────────────────────────────────────────────────────────

  @CreateDateColumn()
  @Index("idx_audit_created_at")
  createdAt!: Date;
}
