name: SDK API Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: sdk-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@swt4
        with:
          fetch-depth: 0 # fetch all tags for version comparison

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install SDK dependencies
        run: npm install
        working-directory: packages/sdk

      - name: Generate API snapshot
        run: nxp api-extractor run --local
        working-directory: packages/sdk

      - name: Enforce API compatibility
        run: npm run check:api
        working-directory: packages/sdk

      - name: Generate SDK API docs
        run: npm run docs
        working-directory: packages/sdk

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/sdk/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
